spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: ACCOUNT
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/account/**

        - id: STOCK
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stock/**

        - id: USER
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**,/api/v1/stocks/**



server:
  port: 8084

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
