spring:
  application:
    name: STOCKS

  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_assignment
    username: root
    password: root11!:R00t
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/